import type { Recipe } from "./recipes";
export const newRecipes: Recipe[] = [
  {
    slug: "firinda-levrek-ve-renkli-sebzeler",
    title: "Fırında Levrek ve Renkli Sebzeler",
    subtitle: "Fırında sebzeler • Limon ve otlar",
    shortDescription:
      "Fırında bütün olarak pişirilen levreğin; patates, kabak, domates ve soğanla tamamlandığı, ferah yoğurtlu sos eşliğinde renkli bir ana yemek.",
    heroDescription:
      "Fırında bütün olarak pişirilen levreğin; patates, kabak, domates ve soğanla tamamlandığı, ferah yoğurtlu sos eşliğinde renkli bir ana yemek.",
    category: "Ana Yemek",
    tags: ["Balık", "Fırında", "Dengeli Tabak"],
    image: "/images/recipes/firinda-levrek-ve-renkli-sebzeler.webp",
    imageAlt:
      "Fırında Levrek ve Renkli Sebzeler — Diyetisyen Utku Karakoç mutfağından",
    featured: false,
    servings: "2 porsiyon",
    prepTime: "15 dk",
    cookTime: "35–40 dk",
    totalTime: "50–55 dk",
    difficulty: "",
    allergens: "Balık, süt ve süt ürünleri",
    nutritionType: "Omnivor",
    ingredients: [
      "2 adet orta boy levrek",
      "2 orta boy patates",
      "1 kabak",
      "2 domates",
      "1 orta boy soğan",
      "1 yemek kaşığı zeytinyağı",
      "1 diş sarımsak",
      "1 limon",
      "Birkaç dal maydanoz",
      "Kekik",
      "Karabiber",
      "Tuz",
      "4 yemek kaşığı yoğurt",
      "1 küçük diş sarımsak",
      "Birkaç damla limon suyu",
      "Bir tutam dereotu",
      "Karabiber",
      "İsteğe bağlı birkaç damla zeytinyağı",
    ],
    steps: [
      "Levrekleri temizleyip iyice yıkayın ve kâğıt havlu ile kurulayın. Balıkların üzerine birkaç çizik atın.",
      "Balıkların iç ve dış kısmını tuz, karabiber ve kekik ile hafifçe tatlandırın. İçlerine limon dilimleri, sarımsak ve birkaç dal maydanoz yerleştirin.",
      "Patatesleri iri küpler, kabağı kalın dilimler, domatesleri iri parçalar ve soğanı kalın dilimler halinde doğrayın.",
      "Sebzeleri fırın tepsisine alın. Zeytinyağının bir kısmını üzerine gezdirip tuz, karabiber ve kekikle harmanlayın.",
      "Patateslerin daha geç pişeceğini düşünerek sebzeleri önceden ısıtılmış 200°C fırında yaklaşık 15 dakika pişirin.",
      "Tepsiyi fırından çıkarın ve levrekleri sebzelerin üzerine yerleştirin. Kalan zeytinyağını balıkların üzerine gezdirin.",
      "Tepsiyi tekrar fırına verin. Balık tamamen pişip derisi güzelce kızarana, sebzeler de yumuşayıp renk alana kadar yaklaşık 20–25 dakika pişirin.",
      "Yoğurtlu sos için yoğurt, ezilmiş sarımsak, limon suyu, dereotu ve karabiberi karıştırın.",
      "Fırından çıkan levreği sebzelerle birlikte servis tabağına alın. Yanında yoğurtlu sos, limon dilimleri ve taze maydanoz ile servis edin.",
    ],
    microNutrients: [
      {
        label: "Omega-3",
        value: "≈ 1,0–1,5 g",
      },
      {
        label: "B12",
        value: "≈ 3–4 µg",
      },
      {
        label: "D vitamini",
        value: "≈ 5–8 µg",
      },
      {
        label: "Selenyum",
        value: "≈ 40–50 µg",
      },
      {
        label: "Potasyum",
        value: "≈ 900–1.000 mg",
      },
      {
        label: "Folat",
        value: "≈ 80–100 µg",
      },
    ],
    dietitianNote:
      "Levrek; yüksek kaliteli protein, B12 vitamini, D vitamini, selenyum ve omega-3 yağ asitleri açısından değerli bir balıktır. Patates ve sebzeler öğüne karbonhidrat, lif, vitamin ve mineral desteği sağlarken yoğurtlu sos protein ve kalsiyum içeriğine katkıda bulunur. Tarifte kullanılan zeytinyağı ve patates miktarı porsiyonun enerji değerini önemli ölçüde etkileyebileceğinden, özellikle enerji kısıtlaması gereken beslenme planlarında porsiyon kontrolü önemlidir.",
    servingSuggestion:
      "Yanında bol limonlu mevsim salatası ile servis edilebilir. Enerji gereksinimine göre patates miktarı azaltılarak yerine ekstra sebze eklenebilir.",
    calculationNote:
      "Bir porsiyon için, paylaşılan tarif belgesindeki yaklaşık değerlerdir. Ürün, gramaj ve pişirme yöntemine göre değişebilir; kişisel gereksinimleri göstermez.",
    calories: 440,
    protein: 38,
    carbs: 36,
    fat: 18,
    fiber: 6,
  },
  {
    slug: "patates-puresi-yataginda-istiridye-mantari",
    title: "Patates Püresi Yatağında İstiridye Mantarı",
    subtitle: "Kremalı mantar • İpeksi patates püresi • Taze maydanoz",
    shortDescription:
      "İpeksi kıvamda patates püresi üzerine tereyağında sotelenmiş istiridye mantarları ve kremalı sosla hazırlanan, doyurucu bir ana yemek.",
    heroDescription:
      "İpeksi kıvamda patates püresi üzerine tereyağında sotelenmiş istiridye mantarları ve kremalı sosla hazırlanan, doyurucu bir ana yemek.",
    category: "Ana Yemek",
    tags: ["Vejetaryen", "Mantar"],
    image: "/images/recipes/patates-puresi-yataginda-istiridye-mantari.webp",
    imageAlt:
      "Patates Püresi Yatağında İstiridye Mantarı — Diyetisyen Utku Karakoç mutfağından",
    featured: false,
    servings: "2 porsiyon",
    prepTime: "15 dk",
    cookTime: "25 dk",
    totalTime: "40 dk",
    difficulty: "",
    allergens: "Süt ve süt ürünleri",
    nutritionType: "Vejetaryen",
    ingredients: [
      "3 orta boy patates",
      "1 yemek kaşığı tereyağı (püre için)",
      "Yarım çay bardağı süt",
      "Tuz ve karabiber",
      "Bir tutam muskat rendesi (isteğe bağlı)",
      "2 büyük avuç istiridye mantarı",
      "1 tatlı kaşığı zeytinyağı",
      "1 yemek kaşığı tereyağı (mantar için)",
      "1 diş sarımsak",
      "3 yemek kaşığı krema",
      "2–3 dal taze maydanoz",
    ],
    steps: [
      "Patatesleri soyup iri parçalar halinde doğrayın. Yumuşayana kadar haşlayın ve suyunu tamamen süzdürün.",
      "Patatesleri sıcakken ezin. Tereyağını ekleyin; sütü azar azar ilave ederek pürüzsüz bir kıvam elde edin. Tuz, karabiber ve isterseniz çok az muskat ekleyin.",
      "İstiridye mantarlarını temizleyip iri parçalar halinde ayırın. Tavayı iyice ısıtın.",
      "Zeytinyağı ve tereyağını ekleyin. Mantarları yüksek ateşte, suyunu bırakıp tekrar çekene kadar soteleyin.",
      "İnce kıyılmış sarımsağı ekleyip 20–30 saniye çevirin.",
      "Ateşi orta seviyeye alın. Kremayı ekleyip 2–3 dakika hafifçe koyulaştırın. Tuz ve karabiberle tatlandırın.",
      "Patates püresini servis tabağının tabanına yayın. Kremalı istiridye mantarlarını üzerine yerleştirin.",
      "Taze maydanozla tamamlayıp sıcak servis edin.",
    ],
    microNutrients: [
      {
        label: "İstiridye mantarı",
        value: "B vitaminleri, potasyum, lif",
      },
      {
        label: "Patates",
        value: "Karbonhidrat, potasyum",
      },
      {
        label: "Süt ürünleri",
        value: "Protein, kalsiyum",
      },
      {
        label: "Maydanoz",
        value: "C vitamini, folat",
      },
    ],
    dietitianNote:
      "Bu tarif; patatesten gelen karbonhidrat, mantar ve süt ürünlerinden gelen protein ile yağ kaynaklarının bir araya geldiği doyurucu bir ana öğün seçeneğidir. Enerji gereksinimine göre yanında yoğurt veya bol mevsim salatasıyla tamamlanabilir.",
    servingSuggestion:
      "Yanında limonlu roka-mevsim salatası veya közlenmiş sebzelerle servis edebilirsiniz.",
    calculationNote:
      "Bir porsiyon için, paylaşılan tarif belgesindeki yaklaşık değerlerdir. Ürün, gramaj ve pişirme yöntemine göre değişebilir; kişisel gereksinimleri göstermez.",
    calories: 470,
    protein: 13,
    carbs: 48,
    fat: 25,
    fiber: 7,
  },
  {
    slug: "citir-tavuklu-taco",
    title: "Çıtır Tavuklu Taco",
    subtitle: "Çıtır tavuk • Mor lahana • Cherry domates • Yoğurtlu sos",
    shortDescription:
      "Yumuşak tortilla içerisinde fırında çıtırlaştırılmış tavuk parçaları, mor lahana, cherry domates ve ferah yoğurtlu sosla hazırlanan pratik bir taco.",
    heroDescription:
      "Yumuşak tortilla içerisinde fırında çıtırlaştırılmış tavuk parçaları, mor lahana, cherry domates ve ferah yoğurtlu sosla hazırlanan pratik bir taco.",
    category: "Ana Yemek",
    tags: ["Yüksek Protein", "Fırında", "Tavuk"],
    image: "/images/recipes/citir-tavuklu-taco.webp",
    imageAlt: "Çıtır Tavuklu Taco — Diyetisyen Utku Karakoç mutfağından",
    featured: false,
    servings: "2 porsiyon",
    prepTime: "15 dk",
    cookTime: "20 dk",
    totalTime: "35 dk",
    difficulty: "",
    allergens: "Gluten, yumurta, süt ve süt ürünleri",
    nutritionType: "Omnivor",
    ingredients: [
      "4 küçük tortilla",
      "2 parça tavuk göğsü",
      "1 yumurta",
      "4–5 yemek kaşığı galeta unu",
      "1 tatlı kaşığı zeytinyağı",
      "Tuz",
      "Karabiber",
      "Pul biber",
      "Toz kırmızı biber",
      "Bir tutam kekik",
      "2 büyük avuç ince kıyılmış mor lahana",
      "8–10 adet cherry domates",
      "Birkaç damla limon suyu",
      "4 yemek kaşığı yoğurt",
      "1 tatlı kaşığı mayonez",
      "1 küçük diş sarımsak",
      "Birkaç damla limon suyu",
      "Dereotu veya maydanoz",
      "Tuz (sos için)",
      "Karabiber (sos için)",
    ],
    steps: [
      "Tavuğu hazırlayın: Tavuk göğsünü ince uzun parçalar halinde kesin. Tuz, karabiber, pul biber, toz kırmızı biber ve kekikle tatlandırın.",
      "Paneleyin: Yumurtayı bir kasede çırpın. Tavukları önce yumurtaya, ardından galeta ununa bulayın.",
      "Çıtırlaştırın: Tavukları yağlı kâğıt serili tepsiye yerleştirin. Üzerlerine az miktarda zeytinyağı gezdirin. 200°C önceden ısıtılmış fırında yaklaşık 18–20 dakika, tavuk tamamen pişip dışı altın rengini alana kadar pişirin. Airfryer da kullanılabilir.",
      "Sosu hazırlayın: Yoğurt, mayonez, ezilmiş sarımsak, limon suyu, dereotu veya maydanoz, tuz ve karabiberi karıştırın.",
      "Sebzeleri hazırlayın: Mor lahanayı ince ince doğrayın. Cherry domatesleri ikiye bölün. Lahanaya birkaç damla limon suyu ve çok az tuz ekleyin.",
      "Tacoları birleştirin: Tortillaları tavada birkaç saniye ısıtın. İçlerine mor lahana ve cherry domatesleri yerleştirin. Üzerine çıtır tavukları koyun ve yoğurtlu sostan gezdirin.",
      "Servis edin: Tortillaları hafifçe kapatıp tahta çubukla sabitleyin ve taze olarak servis edin.",
    ],
    microNutrients: [
      {
        label: "Tavuk",
        value: "Protein",
      },
      {
        label: "Mor lahana",
        value: "Lif",
      },
      {
        label: "Domates",
        value: "Likopen, C vitamini",
      },
      {
        label: "Yoğurt",
        value: "Protein, kalsiyum",
      },
    ],
    dietitianNote:
      "Klasik kızartma yerine fırın veya airfryer kullanmak, tarifin hazırlanmasında kullanılan yağ miktarını kontrol etmeye yardımcı olur. Tacoları bol yeşillikli bir salata ile tamamlayarak daha hacimli ve dengeli bir öğün oluşturabilirsiniz.",
    servingSuggestion:
      "Yanında limonlu yeşil salata, közlenmiş sebzeler veya hafif bir yoğurtlu dip sosla servis edebilirsiniz.",
    calculationNote:
      "Bir porsiyon için, paylaşılan tarif belgesindeki yaklaşık değerlerdir. Ürün, gramaj ve pişirme yöntemine göre değişebilir; kişisel gereksinimleri göstermez.",
    calories: 520,
    protein: 35,
    carbs: 48,
    fat: 21,
    fiber: 6,
  },
  {
    slug: "peynirli-hindi-fumeli-kahvalti-tabagi",
    title: "Peynirli Hindi Fümeli Kahvaltı Tabağı",
    subtitle:
      "Yumurta • Hindi füme • Beyaz peynir • Siyah zeytin • Cherry domates",
    shortDescription:
      "Yumurta, peynir ve hindi fümenin domates ve zeytinle buluştuğu, kolay hazırlanan bir kahvaltı tabağı.",
    heroDescription:
      "Yumurta, peynir ve hindi fümenin domates ve zeytinle buluştuğu, kolay hazırlanan bir kahvaltı tabağı.",
    category: "Kahvaltı",
    tags: ["Yüksek Protein", "Pratik"],
    image: "/images/recipes/peynirli-hindi-fumeli-kahvalti-tabagi.webp",
    imageAlt:
      "Peynirli Hindi Fümeli Kahvaltı Tabağı — Diyetisyen Utku Karakoç mutfağından",
    featured: false,
    servings: "1 porsiyon",
    prepTime: "5 dk",
    cookTime: "10 dk",
    totalTime: "15 dk",
    difficulty: "",
    allergens: "Yumurta, süt ve süt ürünleri",
    nutritionType: "Omnivor",
    ingredients: [
      "2 adet yumurta",
      "2–3 dilim hindi füme",
      "2–3 ince dilim beyaz peynir",
      "5–6 adet cherry domates",
      "5–6 adet siyah zeytin",
      "1 tatlı kaşığı zeytinyağı",
      "Karabiber",
      "Kekik (isteğe bağlı)",
      "İsteğe göre pul biber",
    ],
    steps: [
      "Yumurta karışımını hazırlayın. Yumurtaları bir kaseye kırın. Tuz, karabiber ve isterseniz kekik ekleyerek çırpın.",
      "Omleti pişirin. Tavayı ısıtıp zeytinyağını ekleyin. Yumurta karışımını döküp tamamen pişene kadar kontrollü şekilde pişirin.",
      "Tabağı hazırlayın. Omleti tabağa alın. Hindi füme, beyaz peynir, siyah zeytin ve cherry domatesleri yanına düzenleyin.",
      "Tamamlayın. Üzerine taze çekilmiş karabiber ve isteğe göre kekik serpiştirerek servis edin.",
    ],
    microNutrients: [
      {
        label: "Yumurta",
        value: "Kolin, B vitaminleri",
      },
      {
        label: "Beyaz peynir",
        value: "Kalsiyum",
      },
      {
        label: "Domates",
        value: "Likopen, C vitamini",
      },
      {
        label: "Zeytinyağı",
        value: "Tekli doymamış yağ asitleri",
      },
    ],
    dietitianNote:
      "Bu tabak, karbonhidrat miktarı görece düşük; protein ve yağ içeriği daha yüksek bir kahvaltı seçeneğidir. Günlük enerji gereksinimi ve beslenme hedeflerine göre tam tahıllı ekmek, yulaflı bir seçenek veya meyve eklenerek öğünün karbonhidrat ve lif içeriği artırılabilir. Hindi füme ve peynir gibi işlenmiş/işlenmişe yakın ürünlerde porsiyon ve sodyum içeriğine dikkat edilmesi uygun olur.",
    servingSuggestion:
      "Yanında şekersiz çay veya kahve ile servis edilebilir. Mevsiminde domates, salatalık veya farklı sebzeler eklenerek tabağın sebze çeşitliliği artırılabilir.",
    calculationNote:
      "Bir porsiyon için, paylaşılan tarif belgesindeki yaklaşık değerlerdir. Ürün, gramaj ve pişirme yöntemine göre değişebilir; kişisel gereksinimleri göstermez.",
    calories: 390,
    protein: 28,
    carbs: 8,
    fat: 27,
    fiber: 2,
  },
  {
    slug: "mezgit-kizartma-bezelye-puresi-patates-kizartmasi",
    title: "Mezgit Kızartma, Bezelye Püresi ve Patates Kızartması",
    subtitle: "Şef tarifinden uyarlama",
    shortDescription:
      "Çıtır kaplamalı mezgitin, bezelye püresi ve patates kızartmasıyla buluştuğu; klasik fish & chips yaklaşımından ilham alan restoran sunumlu bir balık tabağı.",
    heroDescription:
      "Çıtır kaplamalı mezgitin, bezelye püresi ve patates kızartmasıyla buluştuğu; klasik fish & chips yaklaşımından ilham alan restoran sunumlu bir balık tabağı.",
    category: "Ana Yemek",
    tags: ["Şef Tarifinden Uyarlama", "Balık", "Deniz Ürünleri"],
    image:
      "/images/recipes/mezgit-kizartma-bezelye-puresi-patates-kizartmasi.webp",
    imageAlt:
      "Mezgit Kızartma, Bezelye Püresi ve Patates Kızartması — tarifin özgün fotoğrafı",
    featured: true,
    servings: "2 porsiyon",
    prepTime: "",
    cookTime: "",
    totalTime: "45–60 dk",
    difficulty: "",
    allergens: "Balık, gluten, yumurta, süt, hardal",
    nutritionType: "Omnivor",
    ingredients: [
      "Mezgit fileto",
      "Un",
      "Yumurta akı",
      "Soda veya bira",
      "Karbonat",
      "Tuz",
      "Karabiber",
      "Kızartma yağı",
      "Limon",
      "Bezelye",
      "Arpacık soğan",
      "Tereyağı",
      "Tavuk veya sebze suyu",
      "Taze nane",
      "Tuz (diğer bileşen 2 için)",
      "Karabiber (diğer bileşen 2 için)",
      "Patates",
      "Kızartma yağı (diğer bileşen 2 için)",
      "Tuz (diğer bileşen 3 için)",
      "Pastörize yumurta sarısı (pişirilmeyen sos için)",
      "Dijon hardalı",
      "Beyaz şarap sirkesi",
      "Sıvı yağ",
      "Haşlanmış yumurta",
      "Kornişon turşu",
      "Kapari",
      "Arpacık soğan (diğer bileşen 2 için)",
    ],
    steps: [
      "Mezgit filetolarını porsiyonlayıp fazla nemini kağıt havlu ile alalım. Tuz ve karabiberle hafifçe lezzetlendirelim.",
      "Un, yumurta akı, soda veya bira ve karbonatı karıştırarak akışkan bir kaplama harcı hazırlayalım.",
      "Mezgit filetolarını hazırladığımız harca bulayalım ve kızgın yağda dışı altın rengini alıp çıtırlaşana kadar kızartalım. Fazla yağını süzdürelim. Balığın iç kısmının da tamamen piştiğinden emin olun.",
      "Bezelye püresi için arpacık soğanı tereyağında yumuşatalım. Bezelye ve suyu ekleyerek pişirelim. Taze naneyi ilave edip blenderdan geçirerek pürüzsüz bir kıvam elde edelim.",
      "Patatesleri kalın çubuklar halinde doğrayalım. İyice kuruttuktan sonra kızartalım. Daha çıtır bir sonuç için iki aşamalı kızartma uygulayabiliriz.",
      "Tartar sosunu hazırlayıp servis zamanına kadar soğukta bekletelim.",
      "Tabağa önce bezelye püresini yerleştirelim. Üzerine çıtır mezgit filetolarını ekleyelim. Patates kızartması ve tartar sosuyla birlikte servis edelim. Limonla tamamlayalım.",
    ],
    microNutrients: [],
    dietitianNote:
      "Klasik bir tabağa beslenme perspektifinden bakalım. Mezgit, kaliteli protein sağlayan yağsız balıklardan biridir. Bezelye püresi ise öğüne bitkisel protein, karbonhidrat ve lif katkısı sağlar. Balığın ve patatesin kızartma yöntemiyle hazırlanması ise öğünün enerji ve yağ içeriğini artırabilir. Bu nedenle tabağı değerlendirirken porsiyon, pişirme yöntemi ve öğünün bütünü birlikte ele alınmalıdır. Yanında taze yeşillik veya limonlu bir salata tercih etmek, öğünün sebze ve lif içeriğini artırmak için iyi bir tamamlayıcı olabilir.",
    calculationNote:
      "Balık, kaplama, kızartma yağı, patates ve sos miktarları standardize edilmediğinden bu tarif için kalori ve makro besin değeri verilmemiştir.",
    tip: "Tom Kerridge’in “Fish and Chips with Pea Purée and Tartare Sauce” tarifinden ilham alınarak mezgit kullanımıyla uyarlanmıştır. Kaynak: https://tomkerridge.com/recipes/fish-and-chips-with-pea-puree-and-tartare-sauce/",
  },
  {
    slug: "inegol-kofte-kekikli-sehriye",
    title: "İnegöl Köfte ve Kekikli Şehriye",
    subtitle: "Klasik köfte • Kekik aromalı şehriye",
    shortDescription:
      "Yumuşak dokulu, dengeli baharat aromalı İnegöl köftelerin; kekik aromasıyla hazırlanan sade şehriye eşliğinde sunulduğu klasik ve doyurucu bir ana öğün.",
    heroDescription:
      "Yumuşak dokulu, dengeli baharat aromalı İnegöl köftelerin; kekik aromasıyla hazırlanan sade şehriye eşliğinde sunulduğu klasik ve doyurucu bir ana öğün.",
    category: "Ana Yemek",
    tags: ["Yüksek Protein", "Ev Yemeği", "Pratik"],
    image: "/images/recipes/inegol-kofte-kekikli-sehriye.webp",
    imageAlt: "İnegöl Köfte ve Kekikli Şehriye — tarifin özgün fotoğrafı",
    featured: false,
    servings: "2 porsiyon",
    prepTime: "",
    cookTime: "",
    totalTime: "30–35 dk",
    difficulty: "",
    allergens: "Gluten; tereyağı kullanılırsa süt",
    nutritionType: "Omnivor",
    ingredients: [
      "Dana kıyma",
      "Galeta unu",
      "Tuz",
      "Karabiber",
      "İsteğe bağlı çok az karbonat",
      "Pişirmek için az miktarda zeytinyağı",
      "Arpa şehriye",
      "Zeytinyağı veya tereyağı",
      "Su veya et/tavuk suyu",
      "Kekik",
      "Tuz (diğer bileşen 2 için)",
      "Karabiber (diğer bileşen 2 için)",
    ],
    steps: [
      "Dana kıymayı galeta unu, tuz, karabiber ve isteğe bağlı çok az karbonat ile birlikte iyice yoğuralım.",
      "Köfte harcını kısa süre dinlendirdikten sonra küçük ve ince İnegöl köfte şeklinde parçalar hazırlayalım.",
      "Isıtılmış tavada köfteleri kontrollü şekilde çevirerek dışları güzelce kızarana ve içleri tamamen pişene kadar pişirelim.",
      "Şehriyeyi az miktarda zeytinyağı veya tereyağı ile birkaç dakika kavuralım.",
      "Sıcak su veya et/tavuk suyunu ekleyelim. Tuz ve karabiberle lezzetlendirelim.",
      "Şehriye suyunu çekmeye başladığında kekiği ekleyelim ve kısık ateşte pişirmeye devam edelim.",
      "Pişen şehriyeyi birkaç dakika dinlendirelim. İnegöl köftelerle birlikte servis edelim.",
    ],
    microNutrients: [],
    dietitianNote:
      "Sade malzemelerle doyurucu bir ana öğün. İnegöl köfte öğünün temel protein kaynağını oluştururken, şehriye karbonhidrat kaynağı olarak enerji sağlar. Kekik ise ekstra enerji eklemeden yemeğe aroma kazandırır. Öğünün sebze ve lif içeriğini artırmak isterseniz yanında mevsim salatası veya sebze ağırlıklı bir garnitür tercih edilebilir.",
    calculationNote:
      "Paylaşılan tarif belgesinde bir porsiyon için verilen yaklaşık değerlerdir. Malzeme gramajları ve pişirme yöntemi sonucu değiştirir.",
    calories: 540,
    protein: 34,
    carbs: 42,
    fat: 25,
    fiber: 2,
  },
  {
    slug: "firinda-tavuk-incik-baharatli-patates-yogurtlu-sebze",
    title: "Fırında Tavuk İncik, Baharatlı Patates ve Yoğurtlu Sebze Tabağı",
    subtitle: "Fırından sofraya • Renkli sebzeler • Yoğurt",
    shortDescription:
      "Fırında baharatlarla pişirilmiş tavuk inciklerin; çıtır patatesler, renkli sebzeler, nar taneleri ve ferah yoğurt eşliğinde sunulduğu doyurucu ve dengeli bir ana öğün.",
    heroDescription:
      "Fırında baharatlarla pişirilmiş tavuk inciklerin; çıtır patatesler, renkli sebzeler, nar taneleri ve ferah yoğurt eşliğinde sunulduğu doyurucu ve dengeli bir ana öğün.",
    category: "Ana Yemek",
    tags: ["Yüksek Protein", "Dengeli Tabak", "Ev Yemeği"],
    image:
      "/images/recipes/firinda-tavuk-incik-baharatli-patates-yogurtlu-sebze.webp",
    imageAlt:
      "Fırında Tavuk İncik, Baharatlı Patates ve Yoğurtlu Sebze Tabağı — tarifin özgün fotoğrafı",
    featured: false,
    servings: "1 porsiyon",
    prepTime: "",
    cookTime: "",
    totalTime: "45–50 dk",
    difficulty: "",
    allergens: "Süt ve süt ürünleri",
    nutritionType: "Omnivor",
    ingredients: [
      "Tavuk incik",
      "Zeytinyağı",
      "Sarımsak",
      "Toz kırmızı biber",
      "Karabiber",
      "Kekik",
      "Tuz",
      "Pul biber",
      "Patates",
      "Zeytinyağı (diğer bileşen 2 için)",
      "Toz kırmızı biber (diğer bileşen 2 için)",
      "Karabiber (diğer bileşen 2 için)",
      "Kekik (diğer bileşen 2 için)",
      "Tuz (diğer bileşen 2 için)",
      "Kıvırcık veya göbek marul",
      "Domates",
      "Renkli biber",
      "Nar taneleri",
      "Limon",
      "Yoğurt",
      "Zeytinyağı (diğer bileşen 3 için)",
      "Tuz (diğer bileşen 3 için)",
      "İsteğe bağlı sarımsak ve kuru nane",
    ],
    steps: [
      "Tavuk incikleri zeytinyağı, ezilmiş sarımsak ve baharatlarla güzelce harmanlayalım.",
      "Patatesleri yuvarlak veya iri parçalar halinde doğrayıp zeytinyağı ve baharatlarla karıştıralım.",
      "Tavuk incikleri ve patatesleri fırın tepsisine yerleştirelim. Önceden ısıtılmış fırında tavuk tamamen pişip dışı güzelce kızarana, patatesler ise dışı hafif çıtır hale gelene kadar pişirelim.",
      "Marul, domates ve biberleri doğrayarak geniş bir kaseye alalım. Üzerine nar tanelerini ekleyelim.",
      "Yoğurdu bir kaseye alıp isteğe bağlı sarımsak, tuz, kuru nane ve birkaç damla zeytinyağı ile karıştıralım.",
      "Tabağın tabanına sebzeleri yerleştirelim. Üzerine fırında pişirdiğimiz tavuk incikleri ve patatesleri ekleyelim.",
      "Yoğurdu tabağın yanında servis edip üzerine biraz zeytinyağı gezdirelim. Limonla tamamlayarak servis edelim.",
    ],
    microNutrients: [],
    dietitianNote:
      "Tek tabakta protein, karbonhidrat ve sebze dengesi. Tavuk incik, kaliteli protein ve çeşitli mikro besinler sağlayan bir hayvansal protein kaynağıdır. Fırında hazırlanan patates öğünün karbonhidrat ihtiyacını karşılarken; marul, domates, biber ve nar tabağa lif, vitamin, mineral ve renk çeşitliliği kazandırır. Yoğurt ise öğüne protein ve kalsiyum katkısı sağlar. Fırında pişirme yönteminin tercih edilmesi, kızartmaya kıyasla daha kontrollü yağ kullanımı sağlar. Özellikle tavuk derisi kullanılıyorsa toplam yağ ve enerji miktarının artabileceği unutulmamalıdır. Yoğurt ve bol sebzeyle birlikte servis edildiğinde tek başına oldukça doyurucu bir ana öğün oluşturabilir. İhtiyaca göre porsiyon miktarı kişisel enerji ve protein gereksinimine göre değiştirilebilir.",
    calculationNote:
      "Paylaşılan tarif belgesinde bir porsiyon için verilen yaklaşık değerlerdir. Malzeme gramajları ve pişirme yöntemi sonucu değiştirir.",
    calories: 650,
    protein: 48,
    carbs: 48,
    fat: 29,
    fiber: 7,
  },
  {
    slug: "izgara-dana-steak-yumurta-meyveli-sporcu-tabagi",
    title: "Izgara Dana Steak, Yumurta ve Meyveli Sporcu Tabağı",
    subtitle: "Sporcu beslenmesi • Yüksek enerji",
    shortDescription:
      "Izgara dana steak, yumurta, avokado ve meyvelerin bir araya geldiği; yüksek protein ve enerji içeriğiyle özellikle enerji ihtiyacı yüksek bireylerin beslenmesine uyarlanabilecek doyurucu bir ana öğün.",
    heroDescription:
      "Izgara dana steak, yumurta, avokado ve meyvelerin bir araya geldiği; yüksek protein ve enerji içeriğiyle özellikle enerji ihtiyacı yüksek bireylerin beslenmesine uyarlanabilecek doyurucu bir ana öğün.",
    category: "Ana Yemek",
    tags: ["Sporcu Beslenmesi", "Yüksek Protein", "Yüksek Enerji"],
    image:
      "/images/recipes/izgara-dana-steak-yumurta-meyveli-sporcu-tabagi.webp",
    imageAlt:
      "Izgara Dana Steak, Yumurta ve Meyveli Sporcu Tabağı — tarifin özgün fotoğrafı",
    featured: false,
    servings: "1 porsiyon",
    prepTime: "",
    cookTime: "",
    totalTime: "20–25 dk",
    difficulty: "",
    allergens: "Yumurta",
    nutritionType: "Omnivor",
    ingredients: [
      "200 g yağsız/az yağlı dana steak",
      "2 adet yumurta",
      "1 diş sarımsak",
      "Taze biberiye",
      "Tuz",
      "Karabiber",
      "100 g avokado",
      "100 g ananas",
      "70 g yaban mersini",
      "100 g muz",
      "10 g zeytinyağı",
      "Mantar · Limon · Pul biber",
    ],
    steps: [
      "Dana steak'i oda sıcaklığına yaklaştırıp fazla nemini kağıt havlu ile alalım. Tuz ve karabiberle her iki tarafını lezzetlendirelim.",
      "Tavayı yüksek ateşte iyice ısıtalım. Zeytinyağını, sarımsağı ve biberiyeyi ekleyelim.",
      "Steak'i tavaya alıp istediğimiz pişirme derecesine göre iki tarafını da mühürleyelim. Pişirme sonrasında birkaç dakika dinlendirelim.",
      "Yumurtaları temiz bir tavada beyazı ve sarısı tamamen pişene kadar kontrollü şekilde pişirin.",
      "Avokadoyu ezerek veya küçük parçalar halinde hazırlayalım. İsteğe bağlı olarak limon, tuz ve karabiberle lezzetlendirelim.",
      "Ananası, yaban mersinlerini ve muzu porsiyonlayalım.",
      "Tabağa steak ve yumurtaları yerleştirelim. Yanına avokado ve meyveleri ekleyerek servis edelim.",
    ],
    microNutrients: [],
    dietitianNote:
      "Sporcu beslenmesinde güçlü bir ana öğün. Bu tabak; yüksek kaliteli protein, karbonhidrat, yağlar ve çeşitli mikro besinleri aynı öğünde bir araya getirir. Dana eti ve yumurta, günlük protein gereksiniminin karşılanmasına katkı sağlayan kaliteli protein kaynaklarıdır. Avokado ise tekli doymamış yağ asitleri ve lif açısından öğüne katkı sağlar. Ananas, muz ve yaban mersini ise karbonhidrat ve çeşitli mikro besinleri sağlayarak özellikle enerji ihtiyacı yüksek sporcularda öğünün karbonhidrat içeriğini destekler. Bu öğünün yaklaşık 980 kcal olması ve yağ içeriğinin yüksek olması nedeniyle antrenmandan hemen önce tüketilecek bir öğün olarak düşünülmemelidir. Yüksek yoğunluklu antrenman öncesinde daha düşük yağlı ve sindirimi kolay bir öğün tercih edilebilir. Bu tabak, antrenman sonrası ana öğün veya günlük enerji ihtiyacı yüksek sporcularda daha uygun bir seçenek olabilir.",
    calculationNote:
      "Paylaşılan tarif belgesinde bir porsiyon için verilen yaklaşık değerlerdir. Malzeme gramajları ve pişirme yöntemi sonucu değiştirir. Kaynakta enerji ve makro değerleri arasında hesap farkı bulunduğundan bu değerler kesin bir hesaplama olarak kullanılmamalıdır.",
    calories: 980,
    protein: 70,
    carbs: 55,
    fat: 67,
    fiber: 9,
  },
  {
    slug: "karidesli-maydanozlu-tagliatelle",
    title: "Karidesli, Maydanozlu Tagliatelle",
    subtitle: "Deniz ürünleri • Taze maydanoz • Limon",
    shortDescription:
      "Karidesin hafif tatlı aroması, taze maydanoz ve limonun ferah dokunuşuyla buluşan; zeytinyağı bazlı, pratik ve aromatik bir tagliatelle tarifi.",
    heroDescription:
      "Karidesin hafif tatlı aroması, taze maydanoz ve limonun ferah dokunuşuyla buluşan; zeytinyağı bazlı, pratik ve aromatik bir tagliatelle tarifi.",
    category: "Ana Yemek",
    tags: ["Deniz Ürünleri", "Yüksek Protein", "Pratik"],
    image: "/images/recipes/karidesli-maydanozlu-tagliatelle.webp",
    imageAlt: "Karidesli, Maydanozlu Tagliatelle — tarifin özgün fotoğrafı",
    featured: false,
    servings: "2 porsiyon",
    prepTime: "",
    cookTime: "",
    totalTime: "25–30 dk",
    difficulty: "",
    allergens: "Kabuklu deniz ürünleri, gluten; makarna çeşidine göre yumurta",
    nutritionType: "Omnivor",
    ingredients: [
      "Tagliatelle makarna",
      "Karides",
      "Zeytinyağı",
      "Sarımsak",
      "Taze maydanoz",
      "Limon",
      "Limon kabuğu rendesi",
      "Tuz",
      "Karabiber",
      "Pul biber (isteğe bağlı)",
    ],
    steps: [
      "Tagliatelle makarnayı bol kaynar ve tuzlu suda, paket üzerindeki pişirme süresine uygun şekilde haşlayalım. Makarna suyundan bir miktar ayıralım.",
      "Karidesleri temizleyip fazla nemini alalım. Tavayı ısıtıp zeytinyağı ve ince doğranmış sarımsağı ekleyelim.",
      "Karidesleri tavaya alıp yüksek ateşte, her iki tarafı da renk alıp tamamen pişene kadar kısa süre soteleyelim.",
      "Haşlanan tagliatelleyi karideslerin bulunduğu tavaya aktaralım. Gerektiğinde ayırdığımız makarna suyundan biraz ekleyerek malzemelerin birbirine iyice karışmasını sağlayalım.",
      "İnce kıyılmış maydanozu, limon suyunu ve limon kabuğu rendesini ekleyelim. Karabiber ve isteğe bağlı pul biberle lezzetlendirelim.",
      "Tüm malzemeleri kısa süre birlikte çevirerek makarnanın aromaları iyice çekmesini sağlayalım.",
      "Tagliatelleyi tabağa alıp üzerine sotelenmiş karidesleri yerleştirelim. Taze maydanoz ve ince rendelenmiş limon kabuğuyla tamamlayarak servis edelim.",
    ],
    microNutrients: [],
    dietitianNote:
      "Sade malzemelerle dengeli bir tabak. Karides, yüksek kaliteli protein sağlayan ve yağ içeriği görece düşük bir deniz ürünüdür. Tagliatelle öğünün temel karbonhidrat kaynağını oluştururken, zeytinyağı yağ kaynağı olarak kullanılır. Maydanoz ve limon tabağa tazelik ve aroma kazandırırken; öğünün sebze ve lif içeriğini artırmak için yanında mevsim yeşillikleri veya limonlu bir salata tercih edilebilir. Tarifte kullanılan zeytinyağı miktarı toplam enerji değerini önemli ölçüde etkileyebileceğinden porsiyona göre kontrollü kullanılması yeterlidir.",
    calculationNote:
      "Paylaşılan tarif belgesinde bir porsiyon için verilen yaklaşık değerlerdir. Malzeme gramajları ve pişirme yöntemi sonucu değiştirir.",
    calories: 560,
    protein: 42,
    carbs: 72,
    fat: 13,
    fiber: 5,
  },
];
