export type Recipe = {
  slug: string;
  title: string;
  subtitle: string;
  shortDescription: string;
  heroDescription: string;
  category: "Kahvaltı" | "Ana Yemek" | "Ara Öğün" | "Tatlı";
  tags: string[];
  image: string;
  imageAlt: string;
  featured?: boolean;
  servings: string;
  prepTime: string;
  cookTime: string;
  totalTime: string;
  difficulty: string;
  calories?: number;
  protein?: number;
  carbs?: number;
  fat?: number;
  fiber?: number;
  allergens?: string;
  nutritionType: string;
  ingredients: string[];
  steps: string[];
  microNutrients: { label: string; value?: string }[];
  dietitianNote: string;
  servingSuggestion?: string;
  calculationNote?: string;
  tip?: string;
};

export const recipes: Recipe[] = [
  {
    slug: "firinda-yaban-mersinli-pankek",
    title: "Fırında Yaban Mersinli Pankek",
    subtitle: "Tam buğday unlu • Şekersiz badem sütlü",
    shortDescription:
      "Kahvaltı ya da ara öğün için hazırlanabilen, lif içeriği desteklenmiş hafif bir pankek tarifi.",
    heroDescription:
      "Yumuşak dokulu, yaban mersiniyle zenginleşen ve ilave şeker içermeyen dengeli bir pankek alternatifi.",
    category: "Kahvaltı",
    tags: ["Tam Tahıl", "İlave şeker yok", "Vejetaryen"],
    image: "/images/recipes/firinda-yaban-mersinli-pankek.webp",
    imageAlt: "Fırın kabında hazırlanan yaban mersinli pankek",
    featured: false,
    servings: "4 porsiyon",
    prepTime: "10 dk",
    cookTime: "20–25 dk",
    totalTime: "30–35 dk",
    difficulty: "Kolay",
    calories: 151,
    protein: 5.4,
    carbs: 24.7,
    fat: 3.7,
    fiber: 3.8,
    allergens: "Buğday (gluten), yumurta, badem",
    nutritionType: "Vejetaryen",
    ingredients: [
      "120 g tam buğday unu",
      "200 ml şekersiz badem sütü",
      "1 adet yumurta",
      "80 g yaban mersini",
      "1 tatlı kaşığı kabartma tozu",
      "1 paket vanilin",
      "1 fiske tuz",
      "5 g sıvı yağ veya yağlı kâğıt",
    ],
    steps: [
      "Fırını 180°C'ye önceden ısıtın.",
      "Yumurta ve badem sütünü bir kapta homojen olana kadar çırpın.",
      "Ayrı kapta tam buğday unu, kabartma tozu, vanilin ve tuzu karıştırın.",
      "Kuru karışımı sıvı karışıma ekleyin; boza kıvamında bir hamur elde edin.",
      "Yaklaşık 20 × 20 cm ölçülerindeki kaba hamuru aktarın ve yüzeyi düzeltin.",
      "Yaban mersinlerini yüzeye eşit şekilde dağıtın.",
      "180°C'de yaklaşık 20–25 dakika pişirin.",
      "10 dakika dinlendirdikten sonra 4 eşit parçaya bölerek servis edin.",
    ],
    microNutrients: [
      { label: "Lif", value: "≈ 3,8 g" },
      { label: "Tam tahıl", value: "Var" },
      { label: "İlave şeker", value: "Eklenmemiş" },
    ],
    dietitianNote:
      "Tam buğday unu ve yaban mersini içeriği sayesinde lif alımına katkı sağlar. Kahvaltıda veya ara öğünde porsiyon kontrolü ile tercih edilebilir.",
    servingSuggestion:
      "İsteğe bağlı olarak üzerine çok az pudra şekeri serpilebilir; bu ekleme temel besin değerlerine dahil değildir.",
  },
  {
    slug: "eksi-mayali-cift-kofteli-hamburger",
    title: "Ekşi Mayalı Ekmekle Çift Köfteli Hamburger",
    subtitle: "Ev yapımı • Yüksek proteinli",
    shortDescription:
      "Yüksek protein ve enerji içeren, dengeli eşlikçilerle birlikte ana öğün olarak planlanabilecek doyurucu bir tarif.",
    heroDescription:
      "Ekşi mayalı ekmek, çift dana köfte ve cheddar ile hazırlanan güçlü bir ana öğün alternatifi.",
    category: "Ana Yemek",
    tags: ["Yüksek Protein", "Ana Öğün", "Omnivor"],
    image: "/images/recipes/eksi-mayali-cift-kofteli-hamburger.webp",
    imageAlt: "İki adet çift köfteli hamburger",
    servings: "1 hamburger",
    prepTime: "10 dk",
    cookTime: "8–12 dk",
    totalTime: "18–22 dk",
    difficulty: "Orta",
    calories: 750,
    protein: 52,
    carbs: 42,
    fat: 40,
    fiber: 3,
    allergens: "Gluten, süt ve süt ürünleri",
    nutritionType: "Omnivor",
    ingredients: [
      "1 adet ekşi mayalı hamburger ekmeği (80 g)",
      "2 adet dana köfte (toplam 200 g)",
      "1 dilim cheddar peyniri (25 g)",
      "2–3 yaprak marul",
      "2–3 dilim domates",
      "3–4 dilim salatalık turşusu",
      "Karabiber",
      "İsteğe bağlı hardal veya ev yapımı sos",
    ],
    steps: [
      "Dana köfteleri karabiber ile hafifçe tatlandırın.",
      "Döküm tavayı iyice ısıtın.",
      "Köfteleri orta-yüksek ateşte her yüzünü 3–4 dakika pişirin.",
      "Pişmeye yakın cheddar peynirini köftelerin üzerine yerleştirin ve eritin.",
      "Hamburger ekmeğini ikiye bölün, kesik yüzeylerini aynı tavada hafifçe kızartın.",
      "Alt ekmeğe marul ve domatesi yerleştirin.",
      "Köfteleri ve peyniri ekleyin; turşuları yerleştirin.",
      "İsteğe bağlı sos ekleyip üst ekmeği kapatarak servis edin.",
    ],
    microNutrients: [
      { label: "Demir", value: "≈ 5 mg" },
      { label: "Çinko", value: "≈ 9 mg" },
      { label: "B12 vitamini", value: "≈ 5 µg" },
      { label: "Sodyum", value: "≈ 1000 mg" },
    ],
    dietitianNote:
      "Protein, demir ve B12 vitamini içeriği güçlü bir ana öğündür. Denge için yanında bol yeşillik veya büyük bir salata ile servis edilmesi uygundur.",
    servingSuggestion:
      "Patates kızartması yerine büyük bir salata veya fırınlanmış sebzelerle eşleştirerek öğünün lif dengesini artırabilirsiniz.",
  },
  {
    slug: "ev-yapimi-dana-kofte",
    title: "Ev Yapımı Dana Köfte",
    subtitle: "Yumuşak dokulu • Fırın / Airfryer / Döküm tava",
    shortDescription:
      "Birden fazla pişirme yöntemine uygun, pratik ve yüksek proteinli ev yapımı köfte tarifi.",
    heroDescription:
      "Yumuşak dokulu dana köfte; airfryer, fırın veya döküm tavada pratik şekilde hazırlanabilir.",
    category: "Ana Yemek",
    tags: ["Yüksek Protein", "Meal Prep", "Aile Sofrası"],
    image: "/images/recipes/ev-yapimi-dana-kofte.webp",
    imageAlt: "Patates ve salata ile servis edilen dana köfte",
    servings: "2 porsiyon / 6 adet",
    prepTime: "15 dk",
    cookTime: "10–18 dk",
    totalTime: "55–60 dk",
    difficulty: "Kolay",
    calories: 282,
    protein: 22,
    carbs: 9.2,
    fat: 16.2,
    fiber: 1.2,
    allergens: "Yumurta, gluten (galeta unu)",
    nutritionType: "Omnivor",
    ingredients: [
      "200 g orta yağlı dana kıyma",
      "40 g kuru soğan",
      "20 g galeta unu",
      "25 g çırpılmış yumurta",
      "1 küçük diş sarımsak",
      "2 g tuz",
      "1/2 çay kaşığı kimyon",
      "1/2 çay kaşığı karabiber",
      "1/4 çay kaşığı pul biber",
      "İsteğe bağlı ince kıyılmış maydanoz",
    ],
    steps: [
      "Kıymayı geniş bir karıştırma kabına alın.",
      "Rendelenmiş soğanı, yumurtayı ve isteğe bağlı sarımsağı ekleyin.",
      "Galeta unu ve baharatları ilave edin.",
      "Tüm malzemeler homojen birleşene kadar 3–4 dakika yoğurun.",
      "Kabın üzerini kapatıp 30 dakika buzdolabında dinlendirin.",
      "Harçtan 6 eşit parça ayırın ve köfte şekli verin.",
      "Döküm tavada, airfryer'da veya 200°C fırında tamamen pişene kadar hazırlayın.",
      "Yanında salata ve kontrollü porsiyon karbonhidrat ile servis edin.",
    ],
    microNutrients: [
      { label: "Demir", value: "≈ 4 mg / porsiyon" },
      { label: "Çinko", value: "≈ 7 mg / porsiyon" },
      { label: "B12 vitamini", value: "≈ 4 µg / porsiyon" },
    ],
    dietitianNote:
      "Protein ve demir yönünden zengin bir temel ana öğündür. Porsiyon kontrolüyle sebze ve tam tahıllı garnitürlerle dengelenebilir.",
    servingSuggestion:
      "Fotoğraftaki gibi fırın patates ve renkli bir salata ile servis edildiğinde öğünün görsel ve besinsel dengesi güçlenir.",
  },
  {
    slug: "kremali-ispanakli-somon",
    title: "Kremalı Ispanaklı Somon",
    subtitle: "Kremalı ıspanak sosu • Limon dokunuşu",
    shortDescription:
      "Omega-3, kaliteli protein ve kremalı ıspanak sosunu bir araya getiren şık bir ana öğün alternatifi.",
    heroDescription:
      "Tavada mühürlenmiş somon filetolarının, kremalı ıspanak sosu ve hafif limon dokunuşuyla tamamlandığı dengeli bir tabak.",
    category: "Ana Yemek",
    tags: ["Omega-3", "Yüksek Protein", "Şık Sunum"],
    image: "/images/recipes/kremali-ispanakli-somon.webp",
    imageAlt: "Kremalı ıspanak sosu ile servis edilen somon fileto",
    featured: true,
    servings: "2 porsiyon",
    prepTime: "10 dk",
    cookTime: "15–20 dk",
    totalTime: "25–30 dk",
    difficulty: "Orta",
    calories: 510,
    protein: 35,
    carbs: 7,
    fat: 38,
    fiber: 2,
    allergens: "Balık, süt ve süt ürünleri",
    nutritionType: "Omnivor",
    ingredients: [
      "2 adet somon fileto (toplam yaklaşık 300 g)",
      "1 yemek kaşığı zeytinyağı",
      "1 diş sarımsak",
      "2 büyük avuç taze ıspanak (yaklaşık 175 g)",
      "Yarım su bardağı krema (yaklaşık 100 ml)",
      "2 yemek kaşığı labne peyniri",
      "1/2 çay kaşığı tuz",
      "Karabiber",
      "Bir tutam muskat rendesi (isteğe bağlı)",
      "Birkaç damla limon suyu",
    ],
    steps: [
      "Somon filetolarını kâğıt havlu ile iyice kurulayın ve her iki yüzünü hafifçe tuz ile karabiberle tatlandırın.",
      "Geniş tabanlı tavayı orta-yüksek ateşte ısıtın; zeytinyağını ekleyin.",
      "Somonları tavaya alın. İlk yüzünü yaklaşık 3–4 dakika, ikinci yüzünü 2–3 dakika pişirerek yüzeyde güzel bir renk oluşturun.",
      "Somonları tavadan alın ve kısa süre dinlendirin.",
      "Aynı tavada ince kıyılmış sarımsağı 20–30 saniye yakmadan çevirin.",
      "Ispanakları ekleyin; yüksek ateşte hacmi küçülüp suyunu büyük ölçüde çekene kadar 1–2 dakika soteleyin.",
      "Ateşi orta-düşük seviyeye alın. Kremayı ve labneyi ekleyip pürüzsüz, parlak ve hafif koyu bir sos elde edene kadar karıştırın. İsteğe bağlı çok az muskat ekleyin.",
      "Somonları sosun üzerine tekrar yerleştirin ve kısık ateşte 2–3 dakika daha pişirerek tamamen hazır hale getirin.",
      "Ocaktan aldıktan sonra birkaç damla limon suyu ekleyin; sosu tabana yayarak somonu üzerine yerleştirip sıcak servis edin.",
    ],
    microNutrients: [
      { label: "Omega-3", value: "≈ 2,5–3,0 g" },
      { label: "B12 vitamini", value: "≈ 4–5 µg" },
      { label: "D vitamini", value: "≈ 12–15 µg" },
      { label: "Selenyum", value: "≈ 40–50 µg" },
      { label: "Potasyum", value: "≈ 700 mg" },
      { label: "Folat", value: "≈ 100 µg" },
      { label: "Fosfor" },
      { label: "Magnezyum" },
      { label: "Demir" },
      { label: "Kalsiyum" },
    ],
    dietitianNote:
      "Somon; yüksek kaliteli protein, omega-3 yağ asitleri, B12 vitamini, D vitamini ve selenyum açısından zengindir. Ispanak ise folat, magnezyum, potasyum ve lif içeriğiyle öğüne katkı sağlar. Krema ve labne nedeniyle porsiyon kontrolü önemlidir.",
    servingSuggestion:
      "Yanında limonlu mevsim salatası, fırın sebzeler veya enerji gereksinimine göre bulgur, kinoa ya da tam tahıllı ekmek ile servis edilebilir.",
  },
  {
    slug: "tavuk-sote-ve-bulgur-pilavi",
    title: "Tavuk Sote ve Bulgur Pilavı",
    subtitle: "Yüksek proteinli • Dengeli ana öğün",
    shortDescription:
      "Tavuk göğsü, biberler ve bulgur pilavı ile hazırlanan dengeli, doyurucu ve takip etmesi kolay bir öğün.",
    heroDescription:
      "Protein, kompleks karbonhidrat ve sebzeyi aynı tabakta buluşturan düzenli öğün alternatifi.",
    category: "Ana Yemek",
    tags: ["Dengeli Tabak", "Yüksek Protein", "Öğle / Akşam"],
    image: "/images/recipes/tavuk-sote-bulgur.webp",
    imageAlt: "Cam kapta servis edilmiş tavuk sote",
    servings: "2 porsiyon",
    prepTime: "15 dk",
    cookTime: "20–25 dk",
    totalTime: "35–40 dk",
    difficulty: "Kolay",
    calories: 680,
    protein: 58,
    carbs: 72,
    fat: 14,
    fiber: 10,
    allergens: "Buğday (bulgur, gluten)",
    nutritionType: "Omnivor",
    ingredients: [
      "400 g tavuk göğsü",
      "10 g zeytinyağı",
      "70 g kuru soğan",
      "100 g kırmızı kapya biber",
      "70 g yeşil biber",
      "1 diş sarımsak",
      "Tuz, karabiber, kırmızı toz biber, kekik",
      "170 g pilavlık bulgur",
      "10 g zeytinyağı",
      "15 g domates salçası",
      "400 ml su",
      "2 g tuz",
    ],
    steps: [
      "Tavuk göğsünü 2–3 cm küpler halinde doğrayın.",
      "Geniş tavayı ısıtıp zeytinyağını ekleyin.",
      "Tavukları yüksek ateşte 4–5 dakika soteleyin.",
      "Soğan, kırmızı kapya biber, yeşil biber ve sarımsağı ilave edin.",
      "Baharatları ekleyerek orta-yüksek ateşte 5–6 dakika daha pişirin.",
      "Ayrı tencerede zeytinyağı ile salçayı kavurun; bulguru ekleyin.",
      "Suyu ve tuzu ekleyip kısık ateşte 12–15 dakika pişirin.",
      "Bulguru 10 dakika dinlendirip tavuk sote ile birlikte servis edin.",
    ],
    microNutrients: [
      { label: "Fosfor", value: "≈ 500 mg" },
      { label: "Potasyum", value: "≈ 1.050 mg" },
      { label: "Magnezyum", value: "≈ 150 mg" },
      { label: "Selenyum", value: "≈ 45 µg" },
    ],
    dietitianNote:
      "Kompleks karbonhidrat, yüksek protein ve sebze dengesini tek öğünde sunar. Düzenli ana öğün planlamasında sürdürülebilir bir alternatiftir.",
    servingSuggestion:
      "Yanında yoğurt veya mevsim salatası ile servis edildiğinde öğünün hacmi artar, tokluk desteği güçlenir.",
  },
  {
    slug: "sebzeli-yesil-mercimek-corbasi",
    title: "Sebzeli Yeşil Mercimek Çorbası",
    subtitle: "Lifli • Bitkisel proteinli • Doyurucu",
    shortDescription:
      "Yeşil mercimek, havuç, kereviz ve ıspanakla hazırlanan; ana öğüne eşlik edebilen besleyici bir çorba.",
    heroDescription:
      "Mercimeğin bitkisel proteini ile sebzelerin lifini aynı kasede buluşturan, sıcak ve pratik bir ev yemeği.",
    category: "Ana Yemek",
    tags: ["Bitkisel Protein", "Lif", "Vejetaryen"],
    image: "/images/recipes/sebzeli-yesil-mercimek-corbasi.webp",
    imageAlt: "Havuç, kereviz ve ıspanaklı yeşil mercimek çorbası",
    servings: "4 porsiyon",
    prepTime: "15 dk",
    cookTime: "30–35 dk",
    totalTime: "45–50 dk",
    difficulty: "Kolay",
    calories: 260,
    protein: 14,
    carbs: 39,
    fat: 6,
    fiber: 12,
    allergens: "Süt ürünü garnitürü eklenirse süt içerir",
    nutritionType: "Vejetaryen",
    ingredients: [
      "240 g haşlanmış yeşil mercimek",
      "1 orta boy havuç",
      "1 sap kereviz",
      "1 küçük kuru soğan",
      "2 avuç taze ıspanak",
      "1 yemek kaşığı zeytinyağı",
      "750 ml su veya tuzu kontrollü sebze suyu",
      "Kimyon, karabiber ve isteğe göre pul biber",
      "Servis için 1 yemek kaşığı yoğurt (isteğe bağlı)",
    ],
    steps: [
      "Soğan, havuç ve kerevizi küçük doğrayın.",
      "Zeytinyağını tencerede ısıtıp soğanı 2–3 dakika yumuşatın.",
      "Havuç ve kerevizi ekleyip 3 dakika daha çevirin.",
      "Mercimek ve suyu ekleyin, orta ateşte sebzeler yumuşayana kadar pişirin.",
      "Son 3–4 dakikada ıspanağı ve baharatları ekleyin.",
      "İsteğe bağlı yoğurtla sıcak servis edin.",
    ],
    microNutrients: [
      { label: "Folat" },
      { label: "Demir" },
      { label: "Potasyum" },
      { label: "Lif", value: "≈ 12 g" },
    ],
    dietitianNote:
      "Mercimek ve sebzeler sayesinde lif ve bitkisel protein içeriği yüksektir. Yanında yoğurt ve tam tahıllı ekmekle daha dengeli bir ana öğüne dönüştürülebilir.",
    calculationNote:
      "Yaklaşık değerler; mercimek, sebze ve 1 yemek kaşığı zeytinyağı üzerinden hesaplanmıştır. Yoğurt garnitürü hesaba dahil değildir.",
    servingSuggestion:
      "Üzerine taze maydanoz ve birkaç damla limon ekleyerek servis edin.",
  },
  {
    slug: "somonlu-kinoa-kuskonmaz-tabagi",
    title: "Somonlu Kinoa ve Kuşkonmaz Tabağı",
    subtitle: "Omega-3 • Kompleks karbonhidrat • Yeşil sebze",
    shortDescription:
      "Fırınlanmış somon, kinoa ve kuşkonmazla hazırlanan; protein ve lif dengesini bir araya getiren ana öğün.",
    heroDescription:
      "Tek tabakta kaliteli protein, kompleks karbonhidrat ve sebze dengesi sağlayan pratik bir ana öğün alternatifi.",
    category: "Ana Yemek",
    tags: ["Omega-3", "Yüksek Protein", "Dengeli Tabak"],
    image: "/images/recipes/somonlu-kinoa-kuskonmaz.webp",
    imageAlt: "Somon, kinoa ve kuşkonmazdan oluşan dengeli tabak",
    servings: "2 porsiyon",
    prepTime: "10 dk",
    cookTime: "20 dk",
    totalTime: "30 dk",
    difficulty: "Kolay",
    calories: 520,
    protein: 36,
    carbs: 40,
    fat: 24,
    fiber: 7,
    allergens: "Balık",
    nutritionType: "Omnivor",
    ingredients: [
      "2 adet somon fileto (toplam yaklaşık 280–300 g)",
      "120 g pişmiş kinoa",
      "250 g kuşkonmaz",
      "1 yemek kaşığı zeytinyağı",
      "1/2 limon",
      "Karabiber, sarımsak tozu ve dereotu",
    ],
    steps: [
      "Fırını 190°C'ye ısıtın.",
      "Somonu limon, karabiber ve baharatlarla tatlandırın.",
      "Somon ve kuşkonmazı yağlı kâğıt serili tepsiye alın, zeytinyağını paylaştırın.",
      "Somon tamamen pişene kadar yaklaşık 15–20 dakika fırınlayın.",
      "Pişmiş kinoayı ısıtın ve tabağa alın.",
      "Somon ile kuşkonmazı kinoa yanında servis edin.",
    ],
    microNutrients: [
      { label: "Omega-3" },
      { label: "Selenyum" },
      { label: "Magnezyum" },
      { label: "Folat" },
    ],
    dietitianNote:
      "Somon omega-3 ve kaliteli protein; kinoa ise kompleks karbonhidrat ve lif sağlar. Porsiyonlar bireysel enerji gereksinimine göre ayarlanabilir.",
    calculationNote:
      "Yaklaşık değerler somonun doğal yağ içeriği, kinoa miktarı ve kullanılan zeytinyağına göre değişebilir.",
    servingSuggestion:
      "Limon ve taze otlarla servis edin; ekstra sos ekleyecekseniz miktarı kontrollü tutun.",
  },
  {
    slug: "kabak-spagetti-yogurtlu-sos",
    title: "Kabak Spagetti ve Yoğurtlu Sos",
    subtitle: "Hafif • Sebze ağırlıklı • Pratik",
    shortDescription:
      "Kabak şeritleri, bezelye ve cherry domatesle hazırlanan; yoğurtlu sosla tamamlanan hafif bir tabak.",
    heroDescription:
      "Sebze hacmi yüksek, ferah ve hızlı hazırlanabilen bir öğle veya akşam alternatifi.",
    category: "Ana Yemek",
    tags: ["Sebze Ağırlıklı", "Vejetaryen", "Hafif"],
    image: "/images/recipes/kabak-spagetti-yogurtlu-sos.webp",
    imageAlt: "Kabak spagetti, bezelye ve domatesli sebze tabağı",
    servings: "2 porsiyon",
    prepTime: "15 dk",
    cookTime: "10 dk",
    totalTime: "25 dk",
    difficulty: "Kolay",
    calories: 285,
    protein: 14,
    carbs: 24,
    fat: 15,
    fiber: 7,
    allergens: "Süt ve süt ürünleri",
    nutritionType: "Vejetaryen",
    ingredients: [
      "3 orta boy kabak",
      "100 g bezelye",
      "150 g cherry domates",
      "200 g süzme yoğurt",
      "1 tatlı kaşığı zeytinyağı",
      "1 küçük diş sarımsak",
      "Taze fesleğen, karabiber",
    ],
    steps: [
      "Kabakları spiral kesici veya jülyen soyacakla şerit haline getirin.",
      "Zeytinyağını tavada ısıtıp kabakları 2–3 dakika hafifçe soteleyin.",
      "Bezelye ve domatesleri ekleyip 3–4 dakika daha pişirin.",
      "Yoğurdu ezilmiş sarımsak ve karabiberle karıştırın.",
      "Sebzeleri tabağa alın, yoğurtlu sos ve fesleğenle tamamlayın.",
    ],
    microNutrients: [
      { label: "C vitamini" },
      { label: "Potasyum" },
      { label: "Kalsiyum" },
      { label: "Lif", value: "≈ 7 g" },
    ],
    dietitianNote:
      "Sebze hacmi yüksek olduğu için öğüne hacim kazandırır. Enerji gereksinimi yüksek bireylerde yanına tam tahıllı ekmek veya başka bir kompleks karbonhidrat eklenebilir.",
    calculationNote:
      "Yaklaşık değerler; yoğurdun yağ oranı ve kullanılan zeytinyağı miktarına göre değişir.",
  },
  {
    slug: "tavuklu-avokadolu-kinoa-bowl",
    title: "Tavuklu Avokadolu Kinoa Bowl",
    subtitle: "Yüksek protein • Lifli • Tek kasede dengeli",
    shortDescription:
      "Izgara tavuk, avokado, kinoa ve yeşilliklerle hazırlanan doyurucu bir bowl tarifi.",
    heroDescription:
      "Protein, kompleks karbonhidrat, sağlıklı yağ ve sebzeyi aynı kasede buluşturan pratik ana öğün.",
    category: "Ana Yemek",
    tags: ["Yüksek Protein", "Meal Prep", "Dengeli Bowl"],
    image: "/images/recipes/tavuklu-avokadolu-kinoa-bowl.webp",
    imageAlt: "Izgara tavuk, avokado ve kinoalı bowl",
    servings: "2 porsiyon",
    prepTime: "15 dk",
    cookTime: "15 dk",
    totalTime: "30 dk",
    difficulty: "Kolay",
    calories: 560,
    protein: 42,
    carbs: 42,
    fat: 25,
    fiber: 10,
    allergens: "Susam eklenirse susam içerir",
    nutritionType: "Omnivor",
    ingredients: [
      "300 g tavuk göğsü",
      "140 g pişmiş kinoa",
      "1 orta boy avokado",
      "2 avuç roka veya karışık yeşillik",
      "1 yemek kaşığı zeytinyağı",
      "1/2 limon",
      "Karabiber, kekik, sarımsak tozu",
    ],
    steps: [
      "Tavuğu baharatlayıp ızgara tavada tamamen pişirin ve dilimleyin.",
      "Yeşillikleri kaselere paylaştırın.",
      "Kinoayı ve dilimlenmiş avokadoyu ekleyin.",
      "Tavuk dilimlerini üzerine yerleştirin.",
      "Limon ve zeytinyağını karıştırıp bowl üzerine gezdirin.",
    ],
    microNutrients: [
      { label: "Potasyum" },
      { label: "Magnezyum" },
      { label: "B6 vitamini" },
      { label: "Folat" },
    ],
    dietitianNote:
      "Öğün hazırlığı için uygun, protein ve lif dengesi güçlü bir seçenektir. Avokado ve zeytinyağı nedeniyle yağ içeriği yükselebileceğinden porsiyon miktarı kişiye göre ayarlanmalıdır.",
    calculationNote:
      "Yaklaşık değerler avokado büyüklüğü, tavuk miktarı ve yağ kullanımına göre değişebilir.",
  },
  {
    slug: "firin-sebzeli-nohut-bowl",
    title: "Fırın Sebzeli Nohut Bowl",
    subtitle: "Bitkisel protein • Renkli sebzeler • Lifli",
    shortDescription:
      "Nohut, kabak, biber ve fırın sebzeleriyle hazırlanan bitkisel protein odaklı bir bowl.",
    heroDescription:
      "Nohudun doyuruculuğunu fırınlanmış sebzeler ve taze otlarla birleştiren pratik, renkli bir ana öğün.",
    category: "Ana Yemek",
    tags: ["Bitkisel Protein", "Vejetaryen", "Yüksek Lif"],
    image: "/images/recipes/firin-sebzeli-nohut-bowl.webp",
    imageAlt: "Fırın sebzeleri ve nohut ile hazırlanmış bowl",
    servings: "2 porsiyon",
    prepTime: "15 dk",
    cookTime: "25 dk",
    totalTime: "40 dk",
    difficulty: "Kolay",
    calories: 430,
    protein: 16,
    carbs: 54,
    fat: 16,
    fiber: 14,
    allergens: "Belirgin majör alerjen içermez; kullanılan ürün etiketlerini kontrol edin",
    nutritionType: "Vejetaryen",
    ingredients: [
      "300 g haşlanmış nohut",
      "1 küçük kabak",
      "1 kırmızı kapya biber",
      "1 küçük sarı biber",
      "1/2 kırmızı soğan",
      "1 yemek kaşığı zeytinyağı",
      "Maydanoz, kimyon, karabiber, toz kırmızı biber",
      "1/2 limon",
    ],
    steps: [
      "Fırını 200°C'ye ısıtın.",
      "Sebzeleri iri küpler halinde doğrayın.",
      "Nohut ve sebzeleri zeytinyağı ve baharatlarla harmanlayın.",
      "Tepsiye yayıp 20–25 dakika, kenarları kızarana kadar fırınlayın.",
      "Limon ve maydanozla tamamlayarak sıcak veya ılık servis edin.",
    ],
    microNutrients: [
      { label: "Folat" },
      { label: "Demir" },
      { label: "Magnezyum" },
      { label: "Lif", value: "≈ 14 g" },
    ],
    dietitianNote:
      "Nohut, bitkisel protein ve lif sağlar. Demir emilimini desteklemek için limon veya başka bir C vitamini kaynağıyla eşleştirmek uygundur.",
    calculationNote:
      "Yaklaşık değerler nohut ve yağ miktarı temel alınarak hesaplanmıştır.",
  },
  {
    slug: "akdeniz-feta-salatasi",
    title: "Akdeniz Feta Salatası",
    subtitle: "Bol yeşillik • Feta • Zeytinyağı",
    shortDescription:
      "Yeşillik, domates, mısır ve feta peyniriyle hazırlanan; ferah ve hızlı bir salata.",
    heroDescription:
      "Renkli sebzeleri peynir ve zeytinyağıyla tamamlayan, öğün hacmini artıran Akdeniz esintili salata.",
    category: "Ana Yemek",
    tags: ["Akdeniz Tipi", "Vejetaryen", "Pratik"],
    image: "/images/recipes/akdeniz-feta-salatasi.webp",
    imageAlt: "Feta peyniri, domates ve yeşillikli Akdeniz salatası",
    servings: "2 porsiyon",
    prepTime: "12 dk",
    cookTime: "0 dk",
    totalTime: "12 dk",
    difficulty: "Çok kolay",
    calories: 310,
    protein: 12,
    carbs: 22,
    fat: 20,
    fiber: 6,
    allergens: "Süt ve süt ürünleri",
    nutritionType: "Vejetaryen",
    ingredients: [
      "4 avuç karışık yeşillik",
      "200 g cherry domates",
      "80 g feta veya az tuzlu beyaz peynir",
      "80 g haşlanmış mısır",
      "1 küçük salatalık",
      "1 yemek kaşığı zeytinyağı",
      "1 yemek kaşığı limon suyu",
      "Kekik ve karabiber",
    ],
    steps: [
      "Yeşillikleri yıkayıp iyice kurulayın.",
      "Domates ve salatalığı doğrayın.",
      "Sebzeleri mısırla birlikte geniş bir kasede karıştırın.",
      "Peyniri küp küp ekleyin.",
      "Zeytinyağı, limon ve kekiği gezdirip servis edin.",
    ],
    microNutrients: [
      { label: "Kalsiyum" },
      { label: "C vitamini" },
      { label: "Folat" },
      { label: "Potasyum" },
    ],
    dietitianNote:
      "Peynir salataya protein ve kalsiyum ekler; tuz içeriği ürün seçimine göre değişir. Düşük tuzlu peynir tercih etmek ve ekstra tuzu sınırlamak iyi bir yaklaşım olabilir.",
    calculationNote:
      "Yaklaşık değerler kullanılan peynirin yağ ve tuz içeriğine göre değişebilir.",
  },
  {
    slug: "orman-meyveli-yogurt-bowl",
    title: "Orman Meyveli Yoğurt Bowl",
    subtitle: "Yoğurt • Orman meyveleri • Chia",
    shortDescription:
      "Yoğurt, orman meyveleri ve chia ile hazırlanan hızlı bir kahvaltı veya ara öğün bowl.",
    heroDescription:
      "Meyvenin doğal tatlılığı ile yoğurdun proteinini birleştiren, hazırlaması dakikalar süren ferah bir bowl.",
    category: "Kahvaltı",
    tags: ["Pratik", "Protein", "İlave şeker yok"],
    image: "/images/recipes/orman-meyveli-yogurt-bowl.webp",
    imageAlt: "Orman meyveleri, yoğurt ve chia ile hazırlanan bowl",
    servings: "1 porsiyon",
    prepTime: "8 dk",
    cookTime: "0 dk",
    totalTime: "8 dk",
    difficulty: "Çok kolay",
    calories: 330,
    protein: 20,
    carbs: 39,
    fat: 10,
    fiber: 9,
    allergens: "Süt ve süt ürünleri",
    nutritionType: "Vejetaryen",
    ingredients: [
      "200 g süzme yoğurt",
      "120 g karışık orman meyvesi",
      "1 yemek kaşığı chia tohumu",
      "1 yemek kaşığı yulaf ezmesi",
      "1 tatlı kaşığı kıyılmış ceviz veya badem",
      "Tarçın",
    ],
    steps: [
      "Yoğurdu kaseye alın.",
      "Orman meyvelerini üzerine yerleştirin.",
      "Chia ve yulafı serpiştirin.",
      "Kıyılmış kuruyemiş ve tarçınla tamamlayın.",
    ],
    microNutrients: [
      { label: "Kalsiyum" },
      { label: "C vitamini" },
      { label: "Manganez" },
      { label: "Lif", value: "≈ 9 g" },
    ],
    dietitianNote:
      "Kahvaltı veya ara öğünde pratik bir seçenektir. Yoğurt seçimine göre protein miktarı değişeceği için etiket bilgisi dikkate alınabilir.",
    calculationNote:
      "Yaklaşık değerler süzme yoğurt ve kuruyemiş miktarına göre değişir.",
  },
  {
    slug: "narenciyeli-cevizli-meyve-salatasi",
    title: "Narenciyeli Cevizli Meyve Salatası",
    subtitle: "Greyfurt • Portakal • Ceviz • Nane",
    shortDescription:
      "Portakal ve greyfurt dilimlerini ceviz ve nane ile birleştiren ferah bir ara öğün.",
    heroDescription:
      "Narenciyenin ferahlığını cevizin doyuruculuğuyla dengeleyen, kısa sürede hazırlanabilen meyve tabağı.",
    category: "Ara Öğün",
    tags: ["C Vitamini", "Pratik", "Bitkisel"],
    image: "/images/recipes/narenciyeli-cevizli-meyve-salatasi.webp",
    imageAlt: "Portakal, greyfurt, ceviz ve naneli meyve salatası",
    servings: "2 porsiyon",
    prepTime: "10 dk",
    cookTime: "0 dk",
    totalTime: "10 dk",
    difficulty: "Çok kolay",
    calories: 210,
    protein: 4,
    carbs: 27,
    fat: 11,
    fiber: 5,
    nutritionType: "Vegan",
    ingredients: [
      "1 büyük portakal",
      "1 orta boy greyfurt",
      "30 g ceviz içi",
      "Taze nane yaprakları",
      "İsteğe göre çok az tarçın",
    ],
    steps: [
      "Portakal ve greyfurtu soyup zarlarını mümkün olduğunca ayırın.",
      "Dilimleri servis tabağına yerleştirin.",
      "Cevizi iri parçalar halinde üzerine ekleyin.",
      "Nane ve isteğe bağlı tarçınla servis edin.",
    ],
    microNutrients: [
      { label: "C vitamini" },
      { label: "Potasyum" },
      { label: "Bitkisel omega-3" },
    ],
    dietitianNote:
      "Meyveyi tek başına tüketmek yerine ceviz gibi bir yağ ve protein kaynağıyla eşleştirmek tokluk süresini destekleyebilir.",
    calculationNote:
      "Yaklaşık değerler meyvelerin büyüklüğü ve ceviz miktarına göre değişebilir.",
  },
  {
    slug: "zeytinyagli-taze-fasulye",
    title: "Zeytinyağlı Taze Fasulye",
    subtitle: "Klasik ev yemeği • Sebze ağırlıklı",
    shortDescription:
      "Domates, soğan ve zeytinyağıyla ağır ateşte pişen klasik taze fasulye tarifi.",
    heroDescription:
      "Sade malzemelerle hazırlanan, sıcak ya da soğuk servis edilebilen lifli bir sebze yemeği.",
    category: "Ana Yemek",
    tags: ["Ev Yemeği", "Sebze", "Vegan"],
    image: "/images/recipes/zeytinyagli-taze-fasulye.webp",
    imageAlt: "Domatesli zeytinyağlı taze fasulye",
    servings: "4 porsiyon",
    prepTime: "15 dk",
    cookTime: "35–40 dk",
    totalTime: "50–55 dk",
    difficulty: "Kolay",
    calories: 220,
    protein: 5,
    carbs: 24,
    fat: 12,
    fiber: 8,
    nutritionType: "Vegan",
    ingredients: [
      "600 g taze fasulye",
      "2 orta boy domates",
      "1 büyük kuru soğan",
      "2 yemek kaşığı zeytinyağı",
      "1 küçük diş sarımsak",
      "150 ml sıcak su",
      "Karabiber ve isteğe göre az tuz",
    ],
    steps: [
      "Fasulyeleri ayıklayıp ikiye bölün.",
      "Soğanı zeytinyağında 3–4 dakika yumuşatın.",
      "Doğranmış domates ve sarımsağı ekleyin.",
      "Fasulyeleri tencereye alın ve kısa süre karıştırın.",
      "Suyu ekleyip kapağı kapalı şekilde kısık ateşte yumuşayana kadar pişirin.",
      "Ilık veya soğuk servis edin.",
    ],
    microNutrients: [
      { label: "Folat" },
      { label: "C vitamini" },
      { label: "Potasyum" },
      { label: "Lif", value: "≈ 8 g" },
    ],
    dietitianNote:
      "Sebze ağırlıklı, lif içeriği iyi bir yemektir. Ana öğün olarak tüketilecekse yoğurt, baklagil veya başka bir protein kaynağıyla tamamlanabilir.",
    calculationNote:
      "Yaklaşık değerler yağ miktarı ve porsiyonlamaya göre değişebilir.",
  },
  {
    slug: "firin-patlicanli-sebze-tabagi",
    title: "Fırın Patlıcanlı Sebze Tabağı",
    subtitle: "Patlıcan • Biber • Domates • Taze otlar",
    shortDescription:
      "Patlıcan, biber ve domatesin fırında yumuşatıldığı, zeytinyağlı ve aromatik bir sebze tabağı.",
    heroDescription:
      "Fırın sebzelerinin yoğun aromasını taze otlarla tamamlayan, ana öğüne eşlik edebilen hafif bir seçenek.",
    category: "Ana Yemek",
    tags: ["Fırın Sebze", "Vegan", "Akdeniz Tipi"],
    image: "/images/recipes/firin-patlicanli-sebze-tabagi.webp",
    imageAlt: "Fırında patlıcan, biber ve domatesli sebze tabağı",
    servings: "4 porsiyon",
    prepTime: "15 dk",
    cookTime: "35 dk",
    totalTime: "50 dk",
    difficulty: "Kolay",
    calories: 245,
    protein: 5,
    carbs: 26,
    fat: 15,
    fiber: 9,
    nutritionType: "Vegan",
    ingredients: [
      "2 orta boy patlıcan",
      "2 kapya biber",
      "2 orta boy domates",
      "1 küçük kuru soğan",
      "2 yemek kaşığı zeytinyağı",
      "1 diş sarımsak",
      "Maydanoz, kekik, karabiber",
    ],
    steps: [
      "Fırını 200°C'ye ısıtın.",
      "Patlıcan, biber ve soğanı iri parçalar halinde doğrayın.",
      "Sebzeleri zeytinyağı ve baharatlarla harmanlayın.",
      "Tepsiye yayıp 25 dakika pişirin.",
      "Domatesleri ve sarımsağı ekleyip 10 dakika daha fırınlayın.",
      "Maydanozla tamamlayarak sıcak veya ılık servis edin.",
    ],
    microNutrients: [
      { label: "Potasyum" },
      { label: "Folat" },
      { label: "C vitamini" },
      { label: "Lif", value: "≈ 9 g" },
    ],
    dietitianNote:
      "Sebze hacmini artırmak için iyi bir eşlikçidir. Ana öğün yapılacaksa nohut, yoğurt veya başka bir protein kaynağıyla tamamlanabilir.",
    calculationNote:
      "Yaklaşık değerler kullanılan zeytinyağı miktarına ve porsiyonlamaya göre değişir.",
  },

];

export const recipeCategories = [
  "Tümü",
  ...Array.from(new Set(recipes.map((recipe) => recipe.category))),
];

export function getRecipeBySlug(slug: string) {
  return recipes.find((recipe) => recipe.slug === slug);
}
