import type { Recipe } from "./recipes";
export type RecipeRow = ReturnType<typeof recipeToRow>;
export function recipeToRow(r: Recipe) {
  return {
    slug: r.slug,
    title: r.title,
    subtitle: r.subtitle,
    description: r.shortDescription,
    hero_description: r.heroDescription,
    category: r.category,
    tags: r.tags,
    cover_image: r.image,
    image_alt: r.imageAlt,
    featured: r.featured ?? false,
    servings: r.servings,
    prep_time: r.prepTime,
    cook_time: r.cookTime,
    total_time: r.totalTime,
    difficulty: r.difficulty,
    calories: r.calories ?? null,
    protein: r.protein ?? null,
    carbs: r.carbs ?? null,
    fat: r.fat ?? null,
    fiber: r.fiber ?? null,
    allergens: r.allergens ?? "",
    nutrition_type: r.nutritionType,
    ingredients: r.ingredients,
    steps: r.steps,
    micro_nutrients: r.microNutrients,
    dietitian_note: r.dietitianNote,
    serving_suggestion: r.servingSuggestion ?? "",
    calculation_note: r.calculationNote ?? "",
    tip: r.tip ?? "",
    status: "published" as string,
  };
}
export function rowToRecipe(r: RecipeRow): Recipe {
  return {
    slug: r.slug,
    title: r.title,
    subtitle: r.subtitle,
    shortDescription: r.description,
    heroDescription: r.hero_description,
    category: r.category,
    tags: r.tags,
    image: r.cover_image,
    imageAlt: r.image_alt,
    featured: r.featured,
    servings: r.servings,
    prepTime: r.prep_time,
    cookTime: r.cook_time,
    totalTime: r.total_time,
    difficulty: r.difficulty,
    calories: r.calories ?? undefined,
    protein: r.protein ?? undefined,
    carbs: r.carbs ?? undefined,
    fat: r.fat ?? undefined,
    fiber: r.fiber ?? undefined,
    allergens: r.allergens,
    nutritionType: r.nutrition_type,
    ingredients: r.ingredients,
    steps: r.steps,
    microNutrients: r.micro_nutrients,
    dietitianNote: r.dietitian_note,
    servingSuggestion: r.serving_suggestion,
    calculationNote: r.calculation_note,
    tip: r.tip,
  };
}
